spring.application.name=demo
logging.level.root=trace

logging.pattern.file=%d{YYYY-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n
# creation of new file and writting logs into it
logging.file.name=logs/application-uat

#1mb file size befire creation of new file
logging.logback.rollingpolicy.max-file-size = 1MB

# for 30 days it will be kept on server
#logging.logback.rollingpolicy.max-history=30

#total zip file size can be of 2gb
logging.logback.rollingpolicy.total-size-cap = 2GB

