spring.application.name=springBootMailsenderapp8


spring.mail.host=smtp.gmail.com
spring.mail.port=587
#data ecryption
spring.mail.username=palankushn@gmail.com
spring.mail.password=rtfx prlq olfp vpf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


