spring.application.name=UserAuthenticaionSpringBootApp12


spring.datasource.url=jdbc:mysql://localhost:3306/UserAuthSpringBootsecurity
spring.datasource.username=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#server.port=9090
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#spring.security.user.name=ankush
#spring.security.user.password=hello


#JWT
jwt.secret=this-is-my-jwt-authorization-takenizaion-ffffffffff
jwt.expiration-ms=3600000

logging.level.org.springframework.security=debug

#github oauth2 configuration
spring.security.oauth2.client.registration.github.client-id=Iv23lifSjbfCIMLRBBCH
spring.security.oauth2.client.registration.github.client-secret=83b97f91bd7d52d81d4181661b9be0161746952e



