spring.application.name=productcatalog1throughVersion


spring.datasource.url=jdbc:mysql://localhost:3306/productCatalog
spring.datasource.username=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#server.port=9090
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymleaf.cache=false

#redis
spring.cache.type = redis
spring.data.redis.host = localhost
spring.data.redis.port = 6379
