spring.application.name=FileManagementSpringbootapp8

spring.datasource.url=jdbc:mysql://localhost:3306/filemanagement
spring.datasource.username=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#server.port=9090
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymleaf.cache=false

#maximum size of one uploaded file
spring.servlet.multipart.max-file-size=20MB

#Maximum size of complete request
spring.servlet.multipart.max-request-size=100MB
